name: Build and Push Container Image

on:
  push:
    branches:
      - main

  pull_request:
    types: [closed] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR was merged to main branch
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged
        run: echo "PR merged to main branch, trigger container image build"
        
      - name: Check commit message
        if: contains(github.event.head_commit.message, 'BUILD_CONTAINER_IMAGE')
        run: echo "Commit message contains 'BUILD_CONTAINER_IMAGE', trigger container image build"  
 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        run: |
          docker build -t bansalworknedu/ridecell-assignment .
          docker push bansalworknedu/ridecell-assignment
